<?php

// this file is automatically generated in 'App\Setting::writeConfig!' 

return [

	'additional_email_bcc' => '0', // Дополнительные адреса bcc
	'email_send_delay' => '0', // задержка отправки email-уведомлений
	'email_categories_created' => '0', // email-уведомления при создании категорий
	'email_categories_updated' => '0', // email-уведомления при изменении категорий
	'email_categories_deleted' => '0', // email-уведомления при удалении категорий
	'email_comments_created' => '0', // email-уведомления при создании комментариев
	'email_comments_updated' => '0', // email-уведомления при изменении комментариев
	'email_comments_deleted' => '0', // email-уведомления при удалении комментариев
	'email_manufacturers_created' => '0', // email-уведомления при создании производителя
	'email_manufacturers_updated' => '0', // email-уведомления при изменении производителя
	'email_manufacturers_deleted' => '0', // email-уведомления при удалении производителя
	'email_orders_created' => '0', // email-уведомления при создании заказа
	'email_orders_updated' => '0', // email-уведомления при изменении заказа
	'email_orders_deleted' => '0', // email-уведомления при отмене заказа
	'email_products_created' => '0', // email-уведомления при создании товаров
	'email_products_updated' => '0', // email-уведомления при изменении товаров
	'email_products_deleted' => '0', // email-уведомления при удалении товаров
	'email_roles_created' => '0', // email-уведомления при создании ролей
	'email_roles_updated' => '0', // email-уведомления при изменении ролей
	'email_roles_deleted' => '0', // email-уведомления при удалении ролей
	'email_settings_updated' => '0', // email-уведомления при изменении настроек
	'email_tasks_created' => '0', // email-уведомления при создании задач/поручений
	'email_tasks_updated' => '0', // email-уведомления при изменении задач/поручений
	'email_tasks_deleted' => '0', // email-уведомления при удалении задач/поручений
	'email_users_created' => '0', // email-уведомления при создании пользователей
	'email_users_updated' => '0', // email-уведомления при изменении пользователей
	'email_users_deleted' => '0', // email-уведомления при удалении пользователей
	'view_products_whitout_price' => '1', // Показывать товары без цены
	'priceless_text' => 'Цену на данный товар уточняйте у менеджера', // Текст, выводимый при отсутствии цены на товар
	'description_wysiwyg' => 'tinymce', // Текстовый редактор для редактирования описания товара
	'modification_wysiwyg' => 'srctablecode', // Текстовый редактор для редактирования модификаций товара
	'workingconditions_wysiwyg' => 'tinymce', // Текстовый редактор для редактирования условий работы товара
	'theme' => 'music', // Выбор темы оформления приложения
	'show_empty_category' => '0', // Отображение пустых категорий
	'display_cart' => '0', // Отображение корзины
	'display_prices' => '1', // Отображение цен на товары
	'display_registration' => '0', // Отображение ссылки на регистрацию
	'display_login' => '0', // Отображение ссылки на вход в профиль пользователя
	'filter_manufacturers' => '1', // Показывать фильтр производителей
	'filter_categories' => '1', // Показывать фильтр категорий
	'filter_subcategories' => '0', // Показывать в фильтре категорий подкатегории

];