<?php

// this file is automatically generated in 'App\Http\Controllers\SettingController::update!' 

return [

	'email_new_order' => '0',
	'email_update_order' => '0',
	'email_new_product' => '0',
	'email_update_product' => '0',
	'email_send_delay' => '0',
	'additional_email_bcc' => '0',
	'view_products_whitout_price' => '1',
	'display_cart' => '0',
	'display_prices' => '0',
	'display_registration' => '0',
	'display_login' => '0',
	'priceless_text' => 'Маша - тварь!',

];