<?php

// this file is automatically generated in 'SettingsTableSeeder::run!' 

return [

	'email_new_order' => '0',
	'email_update_order' => '0',
	'email_new_product' => '0',
	'email_update_product' => '0',
	'email_send_delay' => '0',
	'additional_email_bcc' => '0',
	'view_products_whitout_price' => '1',
	'priceless_text' => 'Цену на данный товар уточняйте у менеджера',
	'wysiwyg' => '0',
	'description_wysiwyg' => '1',
	'modification_wysiwyg' => '1',
	'workingconditions_wysiwyg' => '1',
	'display_cart' => '1',
	'display_prices' => '1',
	'display_registration' => '0',
	'display_login' => '1',
	'display_subcategories' => '1',
	'filter_manufacturers' => '1',
	'filter_categories' => '1',
	'filter_subcategories' => '0',

];